### ISSUE TITLE
Adding GuzzleHttp support

### ISSUE THREAD

**Issue by Ninir** [flint/Stampie#30]
Hi @henrikbjorn,

As GuzzleHttp is out and namespaces change a bit, do you plan to support `guzzlehttp/guzzle`; which namespace is `\GuzzleHttp`, and has a modified API compared to guzzle 3.*?

Tried to do something, but Unit tests are kind of blocking me at this point... :)

**Comment by Ninir** [comment]
I'm currently working on this, but have some issues regarding the new Guzzle API (using Stream as body contents..). Will open a PR so that we can see the work on this!

**Comment by henrikbjorn** [comment]
I merged the PR, please let me know if you have more work to do on this.

**Comment by Ninir** [comment]
Not sure it was ready yet... :/! the guzzle api for 4+ was annoying me and didn't find an appropriate solution.


Gauthier Wallet
Envoyé depuis mon iPhone.

**Comment by henrikbjorn** [comment]
I fixed the test, and it seemed to pass :)

**Comment by henrikbjorn** [comment]
Would you mind checking it out and see if you were done?

**Comment by Ninir** [comment]
Thanks @henrikbjorn 

I was getting information on Guzzle, and here was the [answer](https://github.com/guzzle/guzzle/issues/1049#issuecomment-99549830) I get.
It is not possible to set the body of the request and set files, without the content being a field. Do you get my disappointment? :smile: 
Don't want to check if the content is json, then decode it, then recode-it, etc...
