### ISSUE TITLE
[Suggestion] Remove the phar from the repo

### ISSUE THREAD

**Issue by stof** [flint/Stampie#38]
Having the phar archive in the repo has several drawbacks:

- it makes IDEs supporting phar introspection complain about duplicated class definitions
- the phar may not contain the same code than the repo for a given commit, given that it is built only for releases AFAIK
- people cloning the repo don't care about the phar.

I suggest removing the phar from the repo. If you want to distribute a phar versions of releases, a better solution is to attach the phar to the github release, as done in Behat: https://github.com/Behat/Behat/releases

**Comment by henrikbjorn** [comment]
Done
