### ISSUE TITLE
Please tag a new stable version of the library

### ISSUE THREAD

**Issue by stof** [flint/Stampie#54]
Many changes have been done in the library since the 0.7.0 release in May 2013

**Comment by henrikbjorn** [comment]
https://github.com/flint/Stampie/releases/tag/0.11.0

Have been tagged. There was a 0.10.0 before from last year.

**Comment by stof** [comment]
ah, I missed it because you stopped using the v prefix for tags, and so the list ordering for the tag switcher moved them lower
